version: '3.3'
services:
  storm_demo:
    build:
      context: .
    command:
      - storm
      - jar
      - /app/topology.jar
      - org.apache.storm.flux.Flux
      - --local
      - /app/flux.yml
    environment:
      BOT_NAME: botbotbotbot
      BOT_SERVER: irc.freenode.net
      BOT_CHANNEL: '#pircbotx'
